In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Definindo um Ket: |ψ> e |φ>
ket_psi = np.array([[1], [0]])  # Representa |ψ> no espaço vetorial
ket_phi = np.array([[0], [1]])  # Representa |φ> no espaço vetorial

In [ ]:
# Exibindo com colchetes
print("|ψ> = ")
print(ket_psi)

|ψ> = 
[[1]
 [0]]


In [ ]:
# Exibindo com colchetes
print("|φ> = ")
print(ket_phi)

|φ> = 
[[0]
 [1]]


In [ ]:
# Definindo um Bra: <ψ| e <φ|
bra_psi = ket_psi.conj().T  # <ψ|, transposta conjugada de |ψ>
bra_phi = ket_phi.conj().T  # <φ|, transposta conjugada de |φ>

In [ ]:
# Exibindo com colchetes
print("<ψ| = ")
print(bra_psi)

<ψ| = 
[[1 0]]


In [ ]:
# Exibindo com colchetes
print("<φ| = ")
print(bra_phi)

<φ| = 
[[0 1]]


In [ ]:
# Produto Interno (Bra-Ket): <ψ|φ>
inner_product = np.dot(bra_psi, ket_phi)
print("Produto Interno <ψ|φ>:", inner_product)

Produto Interno <ψ|φ>: [[0]]


In [ ]:
# Produto Externo (Ket-Bra): |ψ><φ|
outer_product = np.dot(ket_psi, bra_phi)
print("Produto Externo |ψ><φ|:\n", outer_product)

Produto Externo |ψ><φ|:
 [[0 1]
 [0 0]]


In [ ]:
# Produto Tensorial (Produto de Kronecker) entre |ψ> e |φ>
tensor_product = np.kron(ket_psi, ket_phi)
print("Produto Tensorial |ψ>|φ>:\n", tensor_product)

Produto Tensorial |ψ>|φ>:
 [[0]
 [1]
 [0]
 [0]]


In [ ]:
# Definindo um Operador: Matriz de Pauli X
operator_X = np.array([[0, 1],
                       [1, 0]])