In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Criando vetores
vetor1 = np.array([1, 2, 3])
vetor2 = np.array([4, 5, 6])

# Exibindo com colchetes
print("Vetor1:")
print(vetor1)
print("Vetor2:")
print(vetor2)

Vetor1:
[1 2 3]
Vetor2:
[4 5 6]


In [3]:
vetor3 = np.array([[1], [2], [3]])
vetor4 = np.array([[4], [5], [6]])
# Exibindo com colchetes
print("Vetor3:")
print(vetor3)
print("Vetor4:")
print(vetor4)

Vetor3:
[[1]
 [2]
 [3]]
Vetor4:
[[4]
 [5]
 [6]]


In [4]:
# Criando matrizes
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

print("Matriz1:")
print(matriz1)
print("Matriz2:")
print(matriz2)

Matriz1:
[[1 2]
 [3 4]]
Matriz2:
[[5 6]
 [7 8]]


In [5]:
# Adição de matrizes
matriz_soma = matriz1 + matriz2
print("Adição de Matrizes:\n", matriz_soma)

Adição de Matrizes:
 [[ 6  8]
 [10 12]]


In [6]:
# Subtração de matrizes
matriz_subtracao = matriz1 - matriz2
print("Subtração de Matrizes:\n", matriz_subtracao)

Subtração de Matrizes:
 [[-4 -4]
 [-4 -4]]


In [7]:
# Multiplicação de matrizes
matriz_multiplicacao = np.dot(matriz1, matriz2)
print("Multiplicação de Matrizes:\n", matriz_multiplicacao)

Multiplicação de Matrizes:
 [[19 22]
 [43 50]]


In [8]:
# Matriz identidade
matriz_identidade = np.eye(2)
print("Matriz Identidade:\n", matriz_identidade)

Matriz Identidade:
 [[1. 0.]
 [0. 1.]]


In [9]:
# Matriz transposta
matriz_transposta = np.transpose(matriz1)
print("Matriz Transposta:\n", matriz_transposta)

Matriz Transposta:
 [[1 3]
 [2 4]]


In [10]:
# Números complexos
complexo1 = np.array([[1 + 2j, 3 + 4j], [5 + 6j, 7 + 8j]])
complexo2 = np.array([[1 - 2j, 3 - 4j], [5 - 6j, 7 - 8j]])

In [11]:
print("complexo1:")
print(complexo1)

complexo1:
[[1.+2.j 3.+4.j]
 [5.+6.j 7.+8.j]]


In [12]:
# Matriz transposta conjugada (também conhecida como adjunta ou hermitiana)
matriz_conjugada_transposta = np.conjugate(np.transpose(complexo1))
print("Matriz Transposta Conjugada:\n", matriz_conjugada_transposta)

Matriz Transposta Conjugada:
 [[1.-2.j 5.-6.j]
 [3.-4.j 7.-8.j]]


In [13]:
# Traço da matriz (soma dos elementos da diagonal principal)
traco_matriz = np.trace(matriz1)
print("Traço da Matriz:", traco_matriz)

Traço da Matriz: 5
